debug

diff --git a/.github/workflows/provision & deploy.yaml b/.github/workflows/provision & deploy.yaml
--- a/.github/workflows/provision & deploy.yaml
+++ b/.github/workflows/provision & deploy.yaml
@@ -38,8 +38,11 @@ jobs:
         id: check_changes
         run: |
           terraform init
+          ls
           terraform refresh
+          ls
           terraform plan -out=tfplan
+          ls
           terraform show -no-color ./tfplan > plan_output.txt
           if [ $? -eq 0 ]; then
             echo "No changes detected. Skipping apply."
@@ -55,6 +58,7 @@ jobs:
       - name: Terraform Apply
         if: steps.check_changes.outputs.no_changes == 'false' && github.event.inputs.action == 'apply'
         run: |
+          ls
           terraform apply -auto-approve ./tfplan
         working-directory: ./terraformfiles
         env:
@@ -64,10 +68,11 @@ jobs:
         if: github.event.inputs.action == 'apply'
         id: extract_ecr_url
         run: |
-          # Extract the ECR URL using terraform show and jq
-          ecr_url=$(terraform show -json | jq -r '.values.root_module.resources[] | select(.type=="aws_ecr_repository") | .values.repository_url')
-          
-          # Export the ECR URL as an environment variable
+          ecr_url=$(terraform show -json | jq -r '.values.root_module.resources[] | select(.type=="aws_ecr_repository") | .values.repository_url // empty')
+          if [ -z "$ecr_url" ]; then
+            echo "Error: ECR URL not found!"
+            exit 1
+          fi
           echo "ecr_url=$ecr_url" >> $GITHUB_ENV
 
       - name: Update deployment.yaml with ECR URL
